pstore-clean: fix compilation errors when using CLANG compiler
GCC compiler will be deprecated in Android N dessert and it
will be replaced with CLANG compiler.

This change removes an unused static function.

Change-Id: Ifee4f069f67ab4d5e5df25876553e46989da1a14
Signed-off-by: Yann Fouassier <yann.fouassier@intel.com>
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-21366
Reviewed-on: https://android.intel.com:443/474177